unit Crash.Android.Symbols;

{ On-device function-name resolution for Android from a .gosym side-file.

  Part of the Crash Reporter library - standalone, EurekaLog-compatible
  crash/exception reporting for Delphi cross-platform targets.

  Why this exists: on Android the deployed .so is stripped to .dynsym
  (a tiny export whitelist) and the linker's version script localizes every Pascal
  symbol, so dladdr resolves no names at runtime - app frames in the report carry
  only "<module>+<offset>". This mirrors the .gol line-number model: a compact
  side-file (the .gosym) generated offline from the UNSTRIPPED build (its .symtab)
  is shipped with the app and read at runtime to fill the Unit/Procedure columns.

  The .gosym (built by tools\gen-android-symfile.ps1) is an address-sorted table
  of (VM address, size, mangled name) + a string table, keyed by the ELF
  .note.gnu.build-id (so it can be matched to the running binary; link the .so
  with --build-id=sha1). Names are stored mangled and demangled here via
  __cxa_demangle, exactly as dladdr names are on the other POSIX targets.

  Lookup is a pure in-memory binary search (the file is read once at startup), so
  it is cheap and allocation-light on the crash path.

  No-op on non-Android targets (the unit still compiles everywhere). }

interface

{ Load the .gosym for the running module and verify it matches (build-id). Safe to
  call once at startup; idempotent. Failure (missing/mismatched file) just leaves
  symbols unavailable - the reporter falls back to module+offset, as before. }
procedure CrashInitAndroidSymbols;

{ True once a matching .gosym is loaded. }
function CrashAndroidSymbolsActive: Boolean;

{ Resolve a code address (absolute runtime) within OUR module to a demangled
  Pascal name. AModuleBase is the module's load base (dladdr dli_fbase).
  ARoutineAddr returns the absolute start address of the containing function (so
  the report can show proc+offset). ASourceFile returns the function's source file
  (e.g. "MyApp.Forms.Main.pas") from DWARF, or '' if unknown - it lets the
  formatter take the unit (correct casing) and split class/method authoritatively.
  Returns False if symbols are unavailable or the address is not covered. }
function CrashAndroidLookupName(const ACodeAddr, AModuleBase: UIntPtr;
  out AName: String; out ARoutineAddr: UIntPtr; out ASourceFile: String): Boolean;

{ Source line for a code address within OUR module, from the .gol side-file
  (same model as Linux/macOS, generated by LNG_ELF). 0 if unavailable. }
function CrashAndroidLookupLine(const ACodeAddr, AModuleBase: UIntPtr): Integer;

implementation

{$IF Defined(ANDROID)}

uses
  System.SysUtils,
  System.Classes,
  System.IOUtils,
  Androidapi.AssetManager,
  Androidapi.NativeActivity,
  Posix.Dlfcn,
  Posix.Stdlib;

const
  GOSY_SIGNATURE = $59534F47; // 'GOSY'
  GOSY_VERSION   = $00020000; // v2: per-entry source-file index + file table
  HEADER_SIZE    = 48;        // +FileTabOff(4)+FileTabSize(4) over v1
  ENTRY_SIZE     = 20;        // UInt64 Addr + UInt32 Size + UInt32 NameOff + UInt32 FileOff
  PT_NOTE        = 4;
  NT_GNU_BUILD_ID = 3;
  // .gol (line numbers, GOLN) - shared format with LNG_ELF / Crash.LineNumbers
  GOLN_SIGNATURE = $4E4C4F47; // 'GOLN'
  GOLN_HDR_SIZE  = 44;        // sig+ver+size+count(16) + ID(16) + StartVA(8) + StartLine(4)
  OP_ADVANCE_ADDR = 252;
  OP_ADVANCE_REL  = 253;
  OP_ADVANCE_ABS  = 254;

function cxa_demangle(const mangled_name: MarshaledAString;
  output_buffer: MarshaledAString; length: NativeInt;
  out status: Integer): MarshaledAString; cdecl;
  external 'libc++abi.a' name '__cxa_demangle';

type
  TBuildId = array[0..15] of Byte;

var
  GLoaded: Boolean = False;
  GData: TBytes = nil;          // the whole .gosym, kept in memory
  GCount: UInt32 = 0;
  GEntriesOff: UInt32 = 0;      // = HEADER_SIZE
  GStrTabOff: UInt32 = 0;
  GStrTabSize: UInt32 = 0;
  GFileTabOff: UInt32 = 0;
  GFileTabSize: UInt32 = 0;
  // .gol decoded line table (address-sorted)
  GGolRelAddrs: TArray<UInt32> = nil; // VM address relative to GGolStartVA
  GGolLines: TArray<Integer> = nil;
  GGolStartVA: UInt64 = 0;

{ ---- ELF build-id of a loaded .so file (self-contained, no dl_iterate_phdr) ---- }

type
  TElf64_Ehdr = packed record
    e_ident: array[0..15] of Byte;
    e_type, e_machine: UInt16;
    e_version: UInt32;
    e_entry, e_phoff, e_shoff: UInt64;
    e_flags: UInt32;
    e_ehsize, e_phentsize, e_phnum, e_shentsize, e_shnum, e_shstrndx: UInt16;
  end;
  TElf64_Phdr = packed record
    p_type, p_flags: UInt32;
    p_offset, p_vaddr, p_paddr, p_filesz, p_memsz, p_align: UInt64;
  end;

function Align4(const V: UInt32): UInt32; inline;
begin
  Result := (V + 3) and not UInt32(3);
end;

function ExtractBuildIdFromNote(const ANote: TBytes; out AId: TBuildId): Boolean;
var
  P, NameSz, DescSz, NType, DescPos: UInt32;
  I: Integer;
begin
  Result := False;
  P := 0;
  while (P + 12) <= UInt32(Length(ANote)) do
  begin
    NameSz := PUInt32(@ANote[P])^;
    DescSz := PUInt32(@ANote[P + 4])^;
    NType  := PUInt32(@ANote[P + 8])^;
    DescPos := P + 12 + Align4(NameSz);
    if (NType = NT_GNU_BUILD_ID) and (DescSz >= SizeOf(TBuildId)) and
       ((DescPos + SizeOf(TBuildId)) <= UInt32(Length(ANote))) then
    begin
      for I := 0 to 15 do
        AId[I] := ANote[DescPos + UInt32(I)];
      Exit(True);
    end;
    Inc(P, 12 + Align4(NameSz) + Align4(DescSz));
  end;
end;

function ReadElfBuildId(const APath: String; out AId: TBuildId): Boolean;
var
  Stream: TFileStream;
  Ehdr: TElf64_Ehdr;
  Phdr: TElf64_Phdr;
  I: Integer;
  Note: TBytes;
begin
  Result := False;
  if not TFile.Exists(APath) then
    Exit;
  try
    Stream := TFileStream.Create(APath, fmOpenRead or fmShareDenyNone);
    try
      if Stream.Read(Ehdr, SizeOf(Ehdr)) <> SizeOf(Ehdr) then Exit;
      if (Ehdr.e_ident[0] <> $7F) or (Ehdr.e_ident[1] <> Ord('E')) or
         (Ehdr.e_ident[2] <> Ord('L')) or (Ehdr.e_ident[3] <> Ord('F')) then Exit;
      for I := 0 to Ehdr.e_phnum - 1 do
      begin
        Stream.Position := Int64(Ehdr.e_phoff) + Int64(I) * Ehdr.e_phentsize;
        if Stream.Read(Phdr, SizeOf(Phdr)) <> SizeOf(Phdr) then Break;
        if Phdr.p_type <> PT_NOTE then Continue;
        if (Phdr.p_filesz = 0) or (Phdr.p_filesz > 1024 * 1024) then Continue;
        SetLength(Note, Phdr.p_filesz);
        Stream.Position := Int64(Phdr.p_offset);
        if Stream.Read(Note[0], Length(Note)) <> Length(Note) then Continue;
        if ExtractBuildIdFromNote(Note, AId) then
          Exit(True);
      end;
    finally
      Stream.Free;
    end;
  except
    Result := False;
  end;
end;

{ ---- locate our own module (path + base) via dladdr on this unit's code ---- }

function OurModulePath(out APath: String): Boolean;
var
  Info: dl_info;
begin
  Result := dladdr(UIntPtr(@ReadElfBuildId), Info) <> 0;
  if Result then
    APath := String(Info.dli_fname);
end;

{ ---- side-file bytes: the APK asset is the source of truth ---- }

{ The deployed asset is read straight out of the APK, NOT the copy that
  System.StartUpCopy extracts to the documents dir: that copy is written only
  when the destination does not exist yet ("do not overwrite files" in the RTL),
  so after an app update it still belongs to the previous build and its build-id
  no longer matches the running .so - which is exactly when symbols are wanted.
  The extracted copy stays as a fallback for hosts that ship the side-file
  without packaging it as an asset; both paths go through the same build-id
  check, so a stale one can never produce wrong names. }
function ReadDeployedSideFile(const AAssetName, AFallbackPath: String): TBytes;
var
  Mgr: PAAssetManager;
  Asset: PAAsset;
  Len, Total: Int64;
  Got: Integer;
  M: TMarshaller;
begin
  Result := nil;
  if System.DelphiActivity <> nil then
  begin
    Mgr := ANativeActivity(System.DelphiActivity^).assetManager;
    if Mgr <> nil then
    begin
      Asset := AAssetManager_open(Mgr, M.AsUtf8(AAssetName).ToPointer,
        AASSET_MODE_STREAMING);
      if Asset <> nil then
      try
        Len := Int64(AAsset_getLength(Asset));
        if (Len > 0) and (Len < High(Integer)) then
        begin
          SetLength(Result, Integer(Len));
          Total := 0;
          repeat
            Got := AAsset_read(Asset, @Result[Total], Len - Total);
            if Got <= 0 then
              Break;
            Inc(Total, Got);
          until Total >= Len;
          if Total <> Len then
            Result := nil; // short read - let the fallback have a go
        end;
      finally
        AAsset_close(Asset);
      end;
    end;
  end;
  if (Result = nil) and TFile.Exists(AFallbackPath) then
    try
      Result := TFile.ReadAllBytes(AFallbackPath);
    except
      Result := nil;
    end;
end;

{ ---- .gol (GOLN) line-number decode (same format as Crash.LineNumbers) ---- }

function ReadGolVarInt(const ABytes: TBytes; var APos: Integer; const AEnd: Integer;
  out AValue: UInt32): Boolean;
var
  Shift: Integer;
  B: Byte;
begin
  AValue := 0; Shift := 0; Result := False;
  while APos < AEnd do
  begin
    B := ABytes[APos]; Inc(APos);
    AValue := AValue or (UInt32(B and $7F) shl Shift);
    if (B and $80) = 0 then Exit(True);
    Inc(Shift, 7);
    if Shift >= 32 then Exit(False);
  end;
end;

procedure GolFail;
begin
  GGolRelAddrs := nil; GGolLines := nil;
end;

procedure LoadGol(const B: TBytes; const AId: TBuildId);
var
  Sig, Ver, Sz: UInt32;
  Count, I, Pos, EndPos, J: Integer;
  RelAddr, A1, A2: UInt32;
  Line: Integer;
  Op, Op2: Byte;
begin
  if Length(B) < GOLN_HDR_SIZE then Exit;
  Sig := PUInt32(@B[0])^;
  Ver := PUInt32(@B[4])^;
  Sz  := PUInt32(@B[8])^;
  Count := PInteger(@B[12])^;
  if (Sig <> GOLN_SIGNATURE) or ((Ver shr 16) > 1) or
     (Sz <> UInt32(Length(B))) or (Count < 0) or (UInt32(Count) > UInt32(Length(B))) then
    Exit;
  for J := 0 to 15 do          // build-id at offset 16..31
    if B[16 + J] <> AId[J] then Exit;
  Move(B[32], GGolStartVA, SizeOf(GGolStartVA));
  Line := PInteger(@B[40])^;    // StartLine

  SetLength(GGolRelAddrs, Count + 1);
  SetLength(GGolLines, Count + 1);
  RelAddr := 0;
  GGolRelAddrs[0] := 0;
  GGolLines[0] := Line;
  Pos := GOLN_HDR_SIZE;
  EndPos := Length(B);
  for I := 1 to Count do
  begin
    if Pos >= EndPos then begin GolFail; Exit; end;
    Op := B[Pos]; Inc(Pos);
    if Op < OP_ADVANCE_ADDR then
    begin
      Inc(RelAddr, (Op shr 2) + 1);
      Inc(Line, (Op and 3) + 1);
    end
    else case Op of
      OP_ADVANCE_ADDR:
        begin
          if Pos >= EndPos then begin GolFail; Exit; end;
          Inc(RelAddr, 63);
          Op2 := B[Pos]; Inc(Pos);
          if Op2 < OP_ADVANCE_ADDR then
          begin
            Inc(RelAddr, (Op2 shr 2) + 1);
            Inc(Line, (Op2 and 3) + 1);
          end
          else begin GolFail; Exit; end;
        end;
      OP_ADVANCE_REL, OP_ADVANCE_ABS:
        begin
          if not ReadGolVarInt(B, Pos, EndPos, A1) then begin GolFail; Exit; end;
          if not ReadGolVarInt(B, Pos, EndPos, A2) then begin GolFail; Exit; end;
          Inc(RelAddr, A1 + 1);
          if Op = OP_ADVANCE_REL then Inc(Line, A2 + 1)
          else Line := Integer(A2);
        end;
    else
      begin GolFail; Exit; end;
    end;
    GGolRelAddrs[I] := RelAddr;
    GGolLines[I] := Line;
  end;
end;

function CrashAndroidLookupLine(const ACodeAddr, AModuleBase: UIntPtr): Integer;
var
  VAddr, Rel: UInt64;
  Lo, Hi, Mid, Found: Integer;
begin
  Result := 0;
  if (GGolRelAddrs = nil) or (ACodeAddr < AModuleBase) then Exit;
  VAddr := UInt64(ACodeAddr) - UInt64(AModuleBase);
  if VAddr < GGolStartVA then Exit;
  Rel := VAddr - GGolStartVA;
  if Rel > High(UInt32) then Exit;
  Lo := 0; Hi := High(GGolRelAddrs); Found := -1;
  while Lo <= Hi do
  begin
    Mid := (Lo + Hi) div 2;
    if GGolRelAddrs[Mid] <= UInt32(Rel) then begin Found := Mid; Lo := Mid + 1; end
    else Hi := Mid - 1;
  end;
  // Same unreliability cutoff as TLineNumberInfo.Lookup: a row more than 200
  // bytes behind the address covers an uncoded stretch, not this code.
  if (Found >= 0) and (UInt32(Rel) - GGolRelAddrs[Found] <= 200) then
    Result := GGolLines[Found];
end;

{ ---- .gosym loading ---- }

procedure CrashInitAndroidSymbols;
var
  SoPath, SoName: String;
  ImgId: TBuildId;
  HdrSig, HdrVer, HdrSize, HdrCount: UInt32;
  HdrStrTabOff, HdrStrTabSize, HdrFileTabOff, HdrFileTabSize: UInt32;
  I: Integer;
  Match: Boolean;
begin
  if GLoaded then
    Exit;
  GLoaded := True; // attempt once regardless of outcome

  if not OurModulePath(SoPath) then
    Exit;
  if not ReadElfBuildId(SoPath, ImgId) then
    Exit; // no build-id in the running .so -> can't trust a side-file match

  // Both side-files are deployed into the APK as assets\internal\<so-base>.<ext>;
  // an asset name is the path relative to assets\.
  SoName := ExtractFileName(SoPath);

  // Line numbers (.gol) - independent of the name map below; best-effort.
  LoadGol(ReadDeployedSideFile('internal/' + SoName + '.gol',
    TPath.Combine(TPath.GetDocumentsPath, SoName + '.gol')), ImgId);

  GData := ReadDeployedSideFile('internal/' + SoName + '.gosym',
    TPath.Combine(TPath.GetDocumentsPath, SoName + '.gosym'));
  if Length(GData) < HEADER_SIZE then begin GData := nil; Exit; end;

  HdrSig         := PUInt32(@GData[0])^;
  HdrVer         := PUInt32(@GData[4])^;
  HdrSize        := PUInt32(@GData[8])^;
  HdrCount       := PUInt32(@GData[12])^;
  // build-id at offset 16..31
  HdrStrTabOff   := PUInt32(@GData[32])^;
  HdrStrTabSize  := PUInt32(@GData[36])^;
  HdrFileTabOff  := PUInt32(@GData[40])^;
  HdrFileTabSize := PUInt32(@GData[44])^;

  // Structural layout check: [header][entries][string table][file table], each
  // region inside the file and none overlapping the next. A corrupt offset can
  // then never read a "name" out of a neighbouring region.
  if (HdrSig <> GOSY_SIGNATURE) or ((HdrVer shr 16) <> (GOSY_VERSION shr 16)) or
     (HdrSize <> UInt32(Length(GData))) or
     (HEADER_SIZE + UInt64(HdrCount) * ENTRY_SIZE > UInt64(HdrStrTabOff)) or
     (UInt64(HdrStrTabOff) + HdrStrTabSize > UInt64(HdrFileTabOff)) or
     (UInt64(HdrFileTabOff) + HdrFileTabSize > UInt64(Length(GData))) then
  begin
    GData := nil; Exit;
  end;

  // Verify the .gosym was built for THIS binary (build-id match). A mismatch ->
  // refuse it (wrong names are worse than no names).
  Match := True;
  for I := 0 to 15 do
    if GData[16 + I] <> ImgId[I] then begin Match := False; Break; end;
  if not Match then begin GData := nil; Exit; end;

  GCount := HdrCount;
  GEntriesOff := HEADER_SIZE;
  GStrTabOff := HdrStrTabOff;
  GStrTabSize := HdrStrTabSize;
  GFileTabOff := HdrFileTabOff;
  GFileTabSize := HdrFileTabSize;
end;

function CrashAndroidSymbolsActive: Boolean;
begin
  Result := (GData <> nil) and (GCount > 0);
end;

function EntryAddr(const AIndex: UInt32): UInt64; inline;
begin
  // Move, not PUInt64^: with ENTRY_SIZE=20 every odd entry sits at 4-byte
  // alignment only, and this code also compiles for 32-bit ARM.
  Move(GData[GEntriesOff + AIndex * ENTRY_SIZE], Result, SizeOf(Result));
end;

function BoundedCStr(const AOffset, ALimit: UInt64;
  out AStr: MarshaledAString): Boolean;
// True when GData holds a NUL-terminated string starting at AOffset and fully
// inside [AOffset, ALimit) - ALimit is the owning table's end, so a corrupt
// offset can neither leave the buffer nor read a "name" out of another region.
var
  E, Lim: Integer;
begin
  Result := False;
  AStr := nil;
  if (AOffset >= ALimit) or (ALimit > UInt64(Length(GData))) then
    Exit;
  Lim := Integer(ALimit);
  E := Integer(AOffset);
  while (E < Lim) and (GData[E] <> 0) do
    Inc(E);
  if E >= Lim then
    Exit; // no NUL inside the table - corrupt
  AStr := MarshaledAString(@GData[Integer(AOffset)]);
  Result := True;
end;

function CrashAndroidLookupName(const ACodeAddr, AModuleBase: UIntPtr;
  out AName: String; out ARoutineAddr: UIntPtr; out ASourceFile: String): Boolean;
var
  Target: UInt64;
  Lo, Hi, Mid: Integer;
  Found: Integer;
  EntBase: UInt32;
  Size, NameOff, FileOff, NextAddr: UInt32;
  EntAddr: UInt64;
  Mangled, Demangled, FileStr: MarshaledAString;
  Status: Integer;
begin
  Result := False;
  AName := '';
  ARoutineAddr := 0;
  ASourceFile := '';
  if not CrashAndroidSymbolsActive then
    Exit;
  if ACodeAddr < AModuleBase then
    Exit;
  Target := UInt64(ACodeAddr) - UInt64(AModuleBase); // module-relative VM address

  // binary search: largest entry with Addr <= Target
  Lo := 0; Hi := Integer(GCount) - 1; Found := -1;
  while Lo <= Hi do
  begin
    Mid := (Lo + Hi) div 2;
    if EntryAddr(UInt32(Mid)) <= Target then begin Found := Mid; Lo := Mid + 1; end
    else Hi := Mid - 1;
  end;
  if Found < 0 then
    Exit;

  EntBase := GEntriesOff + UInt32(Found) * ENTRY_SIZE;
  Move(GData[EntBase], EntAddr, SizeOf(EntAddr));
  Size    := PUInt32(@GData[EntBase + 8])^;
  NameOff := PUInt32(@GData[EntBase + 12])^;
  FileOff := PUInt32(@GData[EntBase + 16])^;

  // range check: within [EntAddr, EntAddr+Size) when Size known, else up to the
  // next entry's address.
  if Size > 0 then
  begin
    if Target >= EntAddr + Size then Exit;
  end
  else
  begin
    if UInt32(Found) + 1 < GCount then
    begin
      NextAddr := UInt32(EntryAddr(UInt32(Found) + 1)); // next func start
      if Target >= NextAddr then Exit;
    end;
  end;

  ARoutineAddr := AModuleBase + UIntPtr(EntAddr); // absolute function start

  // source file (NUL-terminated in the file table); FileOff=0 -> unknown
  if (FileOff > 0) and BoundedCStr(UInt64(GFileTabOff) + FileOff,
       UInt64(GFileTabOff) + GFileTabSize, FileStr) then
    ASourceFile := String(AnsiString(FileStr));

  // read mangled name from the string table (NUL-terminated)
  if not BoundedCStr(UInt64(GStrTabOff) + NameOff,
       UInt64(GStrTabOff) + GStrTabSize, Mangled) then
    Exit;

  Demangled := cxa_demangle(Mangled, nil, 0, Status);
  if Demangled = nil then
    AName := String(AnsiString(Mangled))
  else
  begin
    AName := String(Demangled);
    Posix.Stdlib.free(Demangled);
  end;
  Result := AName <> '';
end;

{$ELSE}

procedure CrashInitAndroidSymbols;
begin
end;

function CrashAndroidSymbolsActive: Boolean;
begin
  Result := False;
end;

function CrashAndroidLookupName(const ACodeAddr, AModuleBase: UIntPtr;
  out AName: String; out ARoutineAddr: UIntPtr; out ASourceFile: String): Boolean;
begin
  AName := '';
  ARoutineAddr := 0;
  ASourceFile := '';
  Result := False;
end;

function CrashAndroidLookupLine(const ACodeAddr, AModuleBase: UIntPtr): Integer;
begin
  Result := 0;
end;

{$ENDIF}

end.
