unit Crash.LineNumbers;
{$IFOPT R+} {$DEFINE CRASH_R_WAS_ON} {$ENDIF}
{$IFOPT Q+} {$DEFINE CRASH_Q_WAS_ON} {$ENDIF}
// Disable range and integer-overflow checks for this whole unit.
// The DWARF state-machine decoder relies on UInt32 wraparound semantics
// (Inc(Line.RelAddress, A1 + 1), Line.Line += LineDelta etc.). If the
// enclosing project enables these checks (e.g. DCC_IntegerOverflowCheck /
// DCC_RangeChecking in a release-flavoured config), the loader raises
// EIntOverflow on real .gol files and the reader falls back to "0[+$N]"
// everywhere even with a perfectly valid .gol on disk.
{$R-}
{$Q-}

{ Part of the Crash Reporter library - standalone, EurekaLog-compatible
  crash/exception reporting for Delphi cross-platform targets.

  Derived from Grijjy JustAddCode / ErrorReporting:
    Copyright (c) 2017 Grijjy, Inc. BSD 2-Clause license (see LICENSE.txt).
  Modifications under the same BSD 2-Clause license.

  Utilities for loading line number information from a .gol file. Used by
  the crash reporter to retrieve source line numbers from code addresses.
  Supported on Intel 64-bit macOS and Linux x86-64.

  Line number information files are generated by the Line Number Generator tools
  in the Tools directory: LNG (macOS, from Mach-O + .dSYM) and LNG_ELF (Linux,
  from DWARF embedded in the ELF). Both emit this same platform-independent format,
  decoded below identically on macOS and Linux.

  The .gol file format is loosely modelled after the DWARF __debug_line section
  format:
  * 4 bytes: signature ('GOLN')
  * 4 bytes: version in $MMMMmmmm format. M=Major version, m=minor version.
    A change in minor version should not break the format.
    A reader cannot read a file with a major version that is larger then the
    one the reader is built for.
  * 4 bytes: total size of the .gol file (use for sanity checking)
  * 4 bytes: Number of line number entries in the file.
  * 16 bytes: ID of the executable used to generate the file, for matching the
    .gol to its binary (Mach-O UUID on macOS, ELF .note.gnu.build-id on Linux).
  * 8 bytes: starting VM address.
  * 4 bytes: line number of starting VM address

  What follows is a simple state machine program with instructions to build a
  line number table. Each instruction starts with a single byte (Opcode) and can
  optionally have arguments.

  A simple compression algorithm is used that takes advantage of the facts that
  VM addresses always increase, and the difference between consecutive VM
  addresses is usually small. Similarly, it is efficient if the difference
  between two consecutive line numbers is small. A lot of the time, line numbers
  are increasing, but because of optimization and (compilation) unit changes,
  line numbers may also decrease.

  Opcodes 0-251 are used to update the address and line number, and add a new
  entry all at once. It is used when the difference between the new address and
  the previous address is at most 63, and the difference between the new line
  number and previous line number is between 1 and 4 (inclusive). The Opcode is
  than calculated as:

    Opcode := (LineAdvance - 1) + (AddressAdvance - 1) * 4

  So the mapping looks like:

    Opcode       LineAdvance      AddressAdvance
       0              1                 1
       1              2                 1
       2              3                 1
       3              4                 1
       4              1                 2
       5              2                 2
      ...
      247             4                 62
      248             1                 63
      249             2                 63
      250             3                 63
      251             4                 63

  Opcodes 252-255 have specific meaning. Only 252-254 are currently used:

  252 OP_ADVANCE_ADDR: adds the value 63 to the current address. Is used when
      the total address advance is between 63 and 126 and the line advance is
      between 1 and 4. This opcode should be followed by a regular opcode in
      the 0-247 range to set the final address and line.
  253 OP_ADVANCE_REL: takes 2 VarInt arguments:
      * the address advance. Increments the current address with this value +1
      * the line advance. Increments the current line with this value +1
      Adds an entry to the line number table with the new address and line.
  254 OP_ADVANCE_ABS: takes 2 VarInt arguments:
      * the address advance. Increments the current address with this value +1
      * the line number. Sets the current line to this value (*not +1)
      Adds an entry to the line number table with the new address and line.

  The VarInt format is identical to an unsigned LEB128 format in the DWARF
  specification. Basically, an unsigned integer value is split into chunks of
  7 bits. Each 7-bit chunk is encoded in a 8-bit byte, where the highest bit
  indicates if another 7-bit chunk follows. }

{$SCOPEDENUMS ON}

interface

const
  { Signature of line number files. }
  LINE_NUMBER_SIGNATURE = $4E4C4F47; // 'GOLN'

  { Current version of line number information. }
  LINE_NUMBER_VERSION   = $00010000;

const
  { Opcodes for the state machine program }
  OP_ADVANCE_ADDR = 252;
  OP_ADVANCE_REL  = 253;
  OP_ADVANCE_ABS  = 254;

type
  { .gol file header }
  TLineNumberHeader = packed record
  public
    { File signature. Should be LINE_NUMBER_SIGNATURE }
    Signature: UInt32;

    { File version.
      A change in minor version should not break the format.
      A reader cannot read a file with a major version that is larger then the
      one the reader is built for. }
    Version: UInt32;

    { Total size of the file }
    Size: UInt32;

    { Number of line number entries in the file }
    Count: Int32;

    { ID of the mach-o executable and dSYM that was used to generate the file. }
    ID: TGUID;

    { Starting VM address. }
    StartVMAddress: UInt64;

    { Line number of start address. }
    StartLine: UInt32;
  end;

type
  { Possible values for TLineNumberInfo.Status }
  TLineNumberStatus = (
    { Line number information is available }
    Available,

    { Line number information file (.gol) not found }
    FileNotFound,

    { Line number information file has invalid size (incomplete) }
    InvalidSize,

    { Line number information file has invalid signature }
    InvalidSignature,

    { Line number information file has unsupported version }
    UnsupportedVersion,

    { Line number information file does not match corresponding executable }
    ExecutableIDMismatch,

    { Line number information file is corrupt }
    FileCorrupt,

    { Exception occurred during loading of the file number information file }
    Exception);

type
  { Contains line number information for the currently loaded application. }
  TLineNumberInfo = class
  {$REGION 'Internal Declarations'}
  private type
    TLine = record
      RelAddress: UInt32;
      Line: Int32;
    end;
  private
    FBaseAddress: UInt64;
    FLines: TArray<TLine>;
    FStatus: TLineNumberStatus;
    {$IF Defined(LINUX)}
    FDiagFilename: String;
    FDiagFileExists: Boolean;
    FDiagImageBuildId: TGUID;
    FDiagHeaderId: TGUID;
    FDiagHasDwarf: Boolean;
    FDiagHasDwarfComputed: Boolean;
    {$ENDIF}
    function Load: TLineNumberStatus;
  private
    {$IF (Defined(MACOS64) and not Defined(IOS)) or Defined(LINUX)}
    class function ReadVarInt(var ABuf: PByte; const ABufEnd: PByte;
      out AValue: UInt32): Boolean; static;
    {$ENDIF}
  {$ENDREGION 'Internal Declarations'}
  public
    constructor Create;

    { Returns source line number corresponding to given address, or 0 if not
      available. }
    function Lookup(const AAddress: UIntPtr): Integer;

    { Status of the line number information file. }
    property Status: TLineNumberStatus read FStatus;

    { Diagnostic accessors -- the EL report uses these to print a "why is
      Line=0" reason when the .gol failed to engage. }
    property BaseAddress: UInt64 read FBaseAddress;
    function LineCount: Integer;
    {$IF Defined(LINUX)}
    function DiagImageBuildIdHex: String;
    function DiagFilename: String;
    function DiagFileExists: Boolean;
    function DiagHeaderIdHex: String;
    { True if the running ELF still carries a .debug_line section. When the
      .gol failed to load (Status <> Available) this distinguishes an unstripped
      IDE-built binary -- whose line numbers are recoverable by rebuilding via
      build.cmd -- from a properly stripped release build. }
    function DiagHasDwarf: Boolean;
    {$ENDIF}
  end;

implementation

uses
  System.Generics.Defaults,
  System.Generics.Collections,
  {$IF Defined(MACOS64) and not Defined(IOS)}
  Crash.MacOS.Api,
  Macapi.Foundation,
  Macapi.Helpers,
  System.IOUtils,
  {$ENDIF}
  System.Classes,
  System.SysUtils;

{$IF Defined(MACOS64) and not Defined(IOS)}
const
  libDyld = '/usr/lib/system/libdyld.dylib';

function _dyld_get_image_header(image_index: UInt32): Pmach_header_64;
  cdecl; external libDyld;

function _dyld_get_image_vmaddr_slide(image_index: UInt32): UInt32;
  cdecl; external libDyld;

function GetID: TGUID;
var
  Header: Pmach_header_64;
  Cmd: Pload_command;
  Uuid: Puuid_command absolute Cmd;
  I: Integer;
begin
  Header := _dyld_get_image_header(0);
  Cmd := Pointer(UIntPtr(Header) + SizeOf(mach_header_64));

  for I := 0 to Header.ncmds - 1 do
  begin
    if (Cmd.cmd = LC_UUID) then
      Exit(TGUID(Uuid.uuid));
    Cmd := Pointer(UIntPtr(Cmd) + Cmd.cmdsize);
  end;
  Result := TGUID.Empty;
end;
{$ENDIF}

{$IF Defined(LINUX)}
// File-only approach for image identification + VM slide.
// We deliberately avoid dl_iterate_phdr -- its cdecl callback path SEGV'd
// inside the reporter on some configurations, and a SEGV during exception
// reporting is a double-fault the RTL cannot recover from (silent process
// exit). Instead we do two plain reads:
//   * /proc/self/maps  -> runtime base address of the main exe mapping
//   * ParamStr(0)      -> ELF program headers + .note.gnu.build-id
// No C callbacks, no cdecl boundaries, no chance of a SEGV during the
// reporter's hot path.
type
  Elf64_Ehdr = packed record
    e_ident: array[0..15] of Byte;
    e_type: UInt16;
    e_machine: UInt16;
    e_version: UInt32;
    e_entry: UInt64;
    e_phoff: UInt64;
    e_shoff: UInt64;
    e_flags: UInt32;
    e_ehsize: UInt16;
    e_phentsize: UInt16;
    e_phnum: UInt16;
    e_shentsize: UInt16;
    e_shnum: UInt16;
    e_shstrndx: UInt16;
  end;

  Elf64_Phdr = packed record
    p_type: UInt32;
    p_flags: UInt32;
    p_offset: UInt64;
    p_vaddr: UInt64;
    p_paddr: UInt64;
    p_filesz: UInt64;
    p_memsz: UInt64;
    p_align: UInt64;
  end;

  Elf64_Nhdr = packed record
    n_namesz: UInt32;
    n_descsz: UInt32;
    n_type: UInt32;
  end;

  Elf64_Shdr = packed record
    sh_name: UInt32;       // offset into .shstrtab
    sh_type: UInt32;
    sh_flags: UInt64;
    sh_addr: UInt64;
    sh_offset: UInt64;
    sh_size: UInt64;
    sh_link: UInt32;
    sh_info: UInt32;
    sh_addralign: UInt64;
    sh_entsize: UInt64;
  end;

  TLinuxElfImageInfo = record
    Found: Boolean;
    BaseAddr: NativeUInt;   // VM slide (runtime_base - linker_base)
    BuildID: TGUID;         // first 16 bytes of NT_GNU_BUILD_ID
  end;

const
  PT_LOAD = 1;
  PT_NOTE = 4;
  NT_GNU_BUILD_ID = 3;

function ExtractBuildIDFromNoteBytes(const ANote: TBytes): TGUID;
// Walk PT_NOTE entries (a sequence of Elf64_Nhdr + name + pad + desc + pad)
// looking for NT_GNU_BUILD_ID. Returns first 16 bytes of the descriptor.
var
  Cur, EndOff: Integer;
  Nhdr: Elf64_Nhdr;
  NamePad, DescPad: Integer;
begin
  Result := TGUID.Empty;
  Cur := 0;
  EndOff := Length(ANote);
  while (Cur + SizeOf(Elf64_Nhdr)) <= EndOff do
  begin
    Move(ANote[Cur], Nhdr, SizeOf(Nhdr));
    NamePad := ((Nhdr.n_namesz + 3) shr 2) shl 2;
    DescPad := ((Nhdr.n_descsz + 3) shr 2) shl 2;
    if (Nhdr.n_type = NT_GNU_BUILD_ID) and (Nhdr.n_descsz >= SizeOf(TGUID)) and
       ((Cur + SizeOf(Elf64_Nhdr) + NamePad + Integer(Nhdr.n_descsz)) <= EndOff) then
    begin
      Move(ANote[Cur + SizeOf(Elf64_Nhdr) + NamePad], Result, SizeOf(TGUID));
      Exit;
    end;
    Inc(Cur, SizeOf(Elf64_Nhdr) + NamePad + DescPad);
  end;
end;

function GetLinuxImageInfo: TLinuxElfImageInfo;
// Delphi Linux binaries are always built non-PIE (ET_EXEC, hard-coded base
// 0x400000) -- so runtime slide is 0 and we don't need /proc/self/maps.
// We just open ParamStr(0), walk program headers, and pull the build-id
// out of the PT_NOTE segment. No cdecl callbacks (so no chance of a SEGV
// inside the crash reporter), no /proc pseudo-file reads (TStringList
// silently throws EReadError on those due to size=0 / mmap quirks).
// If a future build adopts -pie / ET_DYN, slide computation must change
// (e.g. compare known function address vs its p_vaddr).
var
  Stream: TFileStream;
  Ehdr: Elf64_Ehdr;
  Phdrs: array of Elf64_Phdr;
  I: Integer;
  Note: TBytes;
begin
  Result.Found := False;
  Result.BaseAddr := 0;
  Result.BuildID := TGUID.Empty;

  try
    Stream := TFileStream.Create(ParamStr(0), fmOpenRead or fmShareDenyNone);
    try
      Stream.ReadBuffer(Ehdr, SizeOf(Ehdr));
      if (Ehdr.e_ident[0] <> $7F) or (Ehdr.e_ident[1] <> Ord('E')) or
         (Ehdr.e_ident[2] <> Ord('L')) or (Ehdr.e_ident[3] <> Ord('F')) then
        Exit;
      if Ehdr.e_phnum = 0 then Exit;
      if Ehdr.e_phentsize <> SizeOf(Elf64_Phdr) then Exit;

      SetLength(Phdrs, Ehdr.e_phnum);
      Stream.Position := Ehdr.e_phoff;
      Stream.ReadBuffer(Phdrs[0], Int64(Ehdr.e_phnum) * SizeOf(Elf64_Phdr));

      // Walk PT_NOTEs looking for NT_GNU_BUILD_ID.
      for I := 0 to High(Phdrs) do
      begin
        if Phdrs[I].p_type <> PT_NOTE then Continue;
        if (Phdrs[I].p_filesz = 0) or (Phdrs[I].p_filesz > 65536) then Continue;
        SetLength(Note, Phdrs[I].p_filesz);
        Stream.Position := Phdrs[I].p_offset;
        Stream.ReadBuffer(Note[0], Phdrs[I].p_filesz);
        Result.BuildID := ExtractBuildIDFromNoteBytes(Note);
        if Result.BuildID <> TGUID.Empty then Break;
      end;
    finally
      Stream.Free;
    end;

    // Slide = 0 for non-PIE EXEC (current Delphi default).
    Result.BaseAddr := 0;

    Result.Found := (Result.BuildID <> TGUID.Empty);
  except
    Result.Found := False;
    Result.BaseAddr := 0;
    Result.BuildID := TGUID.Empty;
  end;
end;

function SectionNameMatches(const AStrtab: TBytes; const AOff: UInt32;
  const ATarget: AnsiString): Boolean;
// Bounded compare of the NUL-terminated section name at AOff in .shstrtab
// against ATarget. Fully bounds-checked -- never reads past AStrtab, so it is
// safe to run on a (possibly malformed) image without risking a fault.
var
  K: Integer;
begin
  Result := False;
  if (AOff >= UInt32(Length(AStrtab))) then
    Exit;
  // need room for ATarget's bytes plus the terminating NUL
  if (Int64(AOff) + Length(ATarget)) >= Int64(Length(AStrtab)) then
    Exit;
  for K := 1 to Length(ATarget) do
    if (AStrtab[Integer(AOff) + K - 1] <> Byte(ATarget[K])) then
      Exit;
  Result := (AStrtab[Integer(AOff) + Length(ATarget)] = 0);
end;

function LinuxImageHasDwarf: Boolean;
// File-only check: does the running ELF still carry a .debug_line section?
// Used only for crash-report diagnostics -- it lets the report tell an
// IDE-built Linux binary (keeps embedded DWARF but has no matching .gol,
// because the IDE drives dcclinux64 directly and skips the MSBuild post-build
// that generates the .gol) apart from a properly stripped release build that
// ships a matching .gol.
// Same safety rules as GetLinuxImageInfo: plain TFileStream reads of
// ParamStr(0), no cdecl callbacks, no /proc pseudo-files, fully guarded.
var
  Stream: TFileStream;
  Ehdr: Elf64_Ehdr;
  Shdrs: array of Elf64_Shdr;
  StrtabBytes: TBytes;
  I: Integer;
begin
  Result := False;
  try
    Stream := TFileStream.Create(ParamStr(0), fmOpenRead or fmShareDenyNone);
    try
      Stream.ReadBuffer(Ehdr, SizeOf(Ehdr));
      if (Ehdr.e_ident[0] <> $7F) or (Ehdr.e_ident[1] <> Ord('E')) or
         (Ehdr.e_ident[2] <> Ord('L')) or (Ehdr.e_ident[3] <> Ord('F')) then
        Exit;
      if (Ehdr.e_shoff = 0) or (Ehdr.e_shnum = 0) then Exit;
      if (Ehdr.e_shentsize <> SizeOf(Elf64_Shdr)) then Exit;
      if (Ehdr.e_shstrndx >= Ehdr.e_shnum) then Exit;  // no usable name table

      SetLength(Shdrs, Ehdr.e_shnum);
      Stream.Position := Ehdr.e_shoff;
      Stream.ReadBuffer(Shdrs[0], Int64(Ehdr.e_shnum) * SizeOf(Elf64_Shdr));

      if (Shdrs[Ehdr.e_shstrndx].sh_size = 0) or
         (Shdrs[Ehdr.e_shstrndx].sh_size > 16 * 1024 * 1024) then Exit;
      SetLength(StrtabBytes, Shdrs[Ehdr.e_shstrndx].sh_size);
      Stream.Position := Shdrs[Ehdr.e_shstrndx].sh_offset;
      Stream.ReadBuffer(StrtabBytes[0], Length(StrtabBytes));

      for I := 0 to Ehdr.e_shnum - 1 do
        if SectionNameMatches(StrtabBytes, Shdrs[I].sh_name, '.debug_line') then
          Exit(True);
    finally
      Stream.Free;
    end;
  except
    Result := False;
  end;
end;
{$ENDIF}


{ TLineNumberInfo }

constructor TLineNumberInfo.Create;
begin
  inherited;
  FStatus := Load;
end;

{$IF Defined(MACOS64) and not Defined(IOS)}
function TLineNumberInfo.Load: TLineNumberStatus;
var
  Filename: String;
  Stream: TFileStream;
  Header: TLineNumberHeader;
  Line: TLine;
  Lines: TArray<TLine>;
  StateMachineProgram: TBytes;
  PC, PCEnd: PByte;
  Opcode: Byte;
  I: Integer;
  A1, A2: UInt32;
  ContentsResourcesPath: String;
begin
  FBaseAddress := 0;
  FLines := nil;

  Filename := ParamStr(0) + '.gol';
  if (not FileExists(Filename)) then
  begin
    { MacOS only allows modules that are signable in the /Contents/MacOS/ path for signed/notarized apps }
    ContentsResourcesPath := NSStrToStr(TNSBundle.Wrap(TNSBundle.OCClass.mainBundle).bundlePath) + '/Contents/Resources/';
    Filename := ContentsResourcesPath + TPath.GetFileName(ParamStr(0)) + '.gol';
  end;

  if (not FileExists(Filename)) then
    Exit(TLineNumberStatus.FileNotFound);

  try
    Stream := TFileStream.Create(Filename, fmOpenRead or fmShareDenyWrite);
    try
      if (Stream.Read(Header, SizeOf(Header)) <> SizeOf(Header)) then
        Exit(TLineNumberStatus.InvalidSize);

      if (Header.Signature <> LINE_NUMBER_SIGNATURE) then
        Exit(TLineNumberStatus.InvalidSignature);

      if ((Header.Version shr 16) > (LINE_NUMBER_VERSION shr 16)) then
        Exit(TLineNumberStatus.UnsupportedVersion);

      if (Header.Size <> Stream.Size) then
        Exit(TLineNumberStatus.InvalidSize);

      if (Header.ID <> GetID) then
        Exit(TLineNumberStatus.ExecutableIDMismatch);

      SetLength(StateMachineProgram, Header.Size - SizeOf(Header));
      if (Stream.Read(StateMachineProgram[0], Length(StateMachineProgram)) <> Length(StateMachineProgram)) then
        Exit(TLineNumberStatus.InvalidSize);
    finally
      Stream.Free;
    end;

    FBaseAddress := Header.StartVMAddress + _dyld_get_image_vmaddr_slide(0);
    SetLength(Lines, Header.Count + 1);

    { Run state machine program }
    Line.RelAddress := 0;
    Line.Line := Header.StartLine;
    Lines[0] := Line;
    PC := @StateMachineProgram[0];
    PCEnd := @StateMachineProgram[Length(StateMachineProgram)];
    for I := 1 to Header.Count do
    begin
      if (PC >= PCEnd) then
        Exit(TLineNumberStatus.FileCorrupt);

      Opcode := PC^;
      Inc(PC);

      if (OpCode < OP_ADVANCE_ADDR) then
      begin
        { 1-byte opcode }
        Inc(Line.RelAddress, (OpCode shr 2) + 1);
        Inc(Line.Line, (OpCode and 3) + 1);
      end
      else case OpCode of
        OP_ADVANCE_ADDR:
          begin
            { 2-byte opcode }
            if (PC >= PCEnd) then
              Exit(TLineNumberStatus.FileCorrupt);

            Inc(Line.RelAddress, 63);
            Opcode := PC^;
            Inc(PC);

            if (Opcode < OP_ADVANCE_ADDR) then
            begin
              Inc(Line.RelAddress, (OpCode shr 2) + 1);
              Inc(Line.Line, (OpCode and 3) + 1);
            end
            else
              Exit(TLineNumberStatus.FileCorrupt);
          end;

        OP_ADVANCE_REL,
        OP_ADVANCE_ABS:
          begin
            { Updates are provided in 2 VarInt parameters }
            if (not ReadVarInt(PC, PCEnd, A1)) then
              Exit(TLineNumberStatus.FileCorrupt);

            if (not ReadVarInt(PC, PCEnd, A2)) then
              Exit(TLineNumberStatus.FileCorrupt);

            Inc(Line.RelAddress, A1 + 1);
            if (Opcode = OP_ADVANCE_REL) then
              Inc(Line.Line, A2 + 1)
            else
              Line.Line := A2;
          end;
      else
        Exit(TLineNumberStatus.FileCorrupt);
      end;

      Lines[I] := Line;
    end;

    FLines := Lines;
    Result := TLineNumberStatus.Available;
  except
    Result := TLineNumberStatus.Exception;
  end;
end;
{$ELSEIF Defined(LINUX)}
// Linux variant of Load. Same on-disk .gol format and same DWARF state
// machine as the macOS path -- only the .gol search path, the ID source
// (ELF .note.gnu.build-id instead of LC_UUID) and the VM slide
// (from /proc/self/maps instead of _dyld_get_image_vmaddr_slide) differ.
function TLineNumberInfo.Load: TLineNumberStatus;
var
  Filename: String;
  Stream: TFileStream;
  Header: TLineNumberHeader;
  Line: TLine;
  Lines: TArray<TLine>;
  StateMachineProgram: TBytes;
  PC, PCEnd: PByte;
  Opcode: Byte;
  I: Integer;
  A1, A2: UInt32;
  ImageInfo: TLinuxElfImageInfo;
begin
  FBaseAddress := 0;
  FLines := nil;

  // Outer guard: any unexpected SIGSEGV/Pascal exception during load must
  // NOT terminate the process -- this code runs inside the crash reporter
  // path on first GetLineNumber call. Failure mode is silent: Status stays
  // Exception, Lookup returns 0, Line column falls back to "0[+$N]" proxy.
  Result := TLineNumberStatus.Exception;
  FDiagImageBuildId := TGUID.Empty;
  FDiagHeaderId := TGUID.Empty;
  FDiagFilename := '';
  FDiagFileExists := False;
  try
    Filename := ParamStr(0) + '.gol';
    FDiagFilename := Filename;
    FDiagFileExists := FileExists(Filename);
    if not FDiagFileExists then
      Exit(TLineNumberStatus.FileNotFound);

    ImageInfo := GetLinuxImageInfo;
    FDiagImageBuildId := ImageInfo.BuildID;
    if (not ImageInfo.Found) or (ImageInfo.BuildID = TGUID.Empty) then
      Exit(TLineNumberStatus.ExecutableIDMismatch);

    Stream := TFileStream.Create(Filename, fmOpenRead or fmShareDenyWrite);
    try
      if (Stream.Read(Header, SizeOf(Header)) <> SizeOf(Header)) then
        Exit(TLineNumberStatus.InvalidSize);
      FDiagHeaderId := Header.ID;

      if (Header.Signature <> LINE_NUMBER_SIGNATURE) then
        Exit(TLineNumberStatus.InvalidSignature);

      if ((Header.Version shr 16) > (LINE_NUMBER_VERSION shr 16)) then
        Exit(TLineNumberStatus.UnsupportedVersion);

      if (Header.Size <> Stream.Size) then
        Exit(TLineNumberStatus.InvalidSize);

      if (Header.ID <> ImageInfo.BuildID) then
        Exit(TLineNumberStatus.ExecutableIDMismatch);

      SetLength(StateMachineProgram, Header.Size - SizeOf(Header));
      if (Stream.Read(StateMachineProgram[0], Length(StateMachineProgram)) <> Length(StateMachineProgram)) then
        Exit(TLineNumberStatus.InvalidSize);
    finally
      Stream.Free;
    end;

    FBaseAddress := Header.StartVMAddress + ImageInfo.BaseAddr;
    SetLength(Lines, Header.Count + 1);

    { Run state machine program (same as macOS branch). }
    Line.RelAddress := 0;
    Line.Line := Header.StartLine;
    Lines[0] := Line;
    PC := @StateMachineProgram[0];
    PCEnd := @StateMachineProgram[Length(StateMachineProgram)];
    for I := 1 to Header.Count do
    begin
      if (PC >= PCEnd) then
        Exit(TLineNumberStatus.FileCorrupt);

      Opcode := PC^;
      Inc(PC);

      if (OpCode < OP_ADVANCE_ADDR) then
      begin
        Inc(Line.RelAddress, (OpCode shr 2) + 1);
        Inc(Line.Line, (OpCode and 3) + 1);
      end
      else case OpCode of
        OP_ADVANCE_ADDR:
          begin
            if (PC >= PCEnd) then
              Exit(TLineNumberStatus.FileCorrupt);
            Inc(Line.RelAddress, 63);
            Opcode := PC^;
            Inc(PC);
            if (Opcode < OP_ADVANCE_ADDR) then
            begin
              Inc(Line.RelAddress, (OpCode shr 2) + 1);
              Inc(Line.Line, (OpCode and 3) + 1);
            end
            else
              Exit(TLineNumberStatus.FileCorrupt);
          end;

        OP_ADVANCE_REL,
        OP_ADVANCE_ABS:
          begin
            if (not ReadVarInt(PC, PCEnd, A1)) then
              Exit(TLineNumberStatus.FileCorrupt);
            if (not ReadVarInt(PC, PCEnd, A2)) then
              Exit(TLineNumberStatus.FileCorrupt);
            Inc(Line.RelAddress, A1 + 1);
            if (Opcode = OP_ADVANCE_REL) then
              Inc(Line.Line, A2 + 1)
            else
              Line.Line := A2;
          end;
      else
        Exit(TLineNumberStatus.FileCorrupt);
      end;

      Lines[I] := Line;
    end;

    FLines := Lines;
    Result := TLineNumberStatus.Available;
  except
    Result := TLineNumberStatus.Exception;
  end;
end;
{$ELSE}
function TLineNumberInfo.Load: TLineNumberStatus;
begin
  Result := TLineNumberStatus.FileNotFound;
end;
{$ENDIF}

function TLineNumberInfo.LineCount: Integer;
begin
  Result := Length(FLines);
end;

{$IF Defined(LINUX)}
function GuidToPlainHex(const G: TGUID): String;
var
  B: array[0..15] of Byte;
  I: Integer;
begin
  Move(G, B, SizeOf(B));
  Result := '';
  for I := 0 to 15 do
    Result := Result + LowerCase(IntToHex(B[I], 2));
end;

function TLineNumberInfo.DiagImageBuildIdHex: String;
begin
  Result := GuidToPlainHex(FDiagImageBuildId);
end;

function TLineNumberInfo.DiagFilename: String;
begin
  Result := FDiagFilename;
end;

function TLineNumberInfo.DiagFileExists: Boolean;
begin
  Result := FDiagFileExists;
end;

function TLineNumberInfo.DiagHeaderIdHex: String;
begin
  Result := GuidToPlainHex(FDiagHeaderId);
end;

function TLineNumberInfo.DiagHasDwarf: Boolean;
// Computed on first use (only the crash-report path asks for it) and cached --
// the eager-init Load path stays a cheap .gol read, with the heavier ELF
// section-table walk deferred to the rare moment a report is actually built.
begin
  if (not FDiagHasDwarfComputed) then
  begin
    FDiagHasDwarf := LinuxImageHasDwarf;
    FDiagHasDwarfComputed := True;
  end;
  Result := FDiagHasDwarf;
end;
{$ENDIF}

function TLineNumberInfo.Lookup(const AAddress: UIntPtr): Integer;
var
  RelAddress, ActualAddress: UInt64;
  Line: TLine;
  Index: Integer;
begin
  if (FStatus <> TLineNumberStatus.Available) then
    Exit(0);

  if (AAddress < FBaseAddress) then
    Exit(0);

  RelAddress := AAddress - FBaseAddress;
  if (RelAddress > $FFFFFFFF) then
    Exit(0);

  Line.RelAddress := RelAddress;
  if (not TArray.BinarySearch<TLine>(FLines, Line, Index, TComparer<TLine>.Construct(
    function(const ALeft, ARight: TLine): Integer
    begin
      Result := ALeft.RelAddress - ARight.RelAddress;
    end)))
  then
    { When there is not an exact match, Index is set to the index in the array
      *before* which we would place the value. }
    Dec(Index);

  if (Index < 0) or (Index >= Length(FLines)) then
    Exit(0);

  { Check if address at this index is close enough to the requested address.
    If not, the resulting line number will be unreliable. This is common for
    addresses which were not available in the dSYM, for example for RTL/VCL/FMX
    addresses when the "Use debug .dcus" project option is not set. }
  ActualAddress := FBaseAddress + FLines[Index].RelAddress;
  if ((AAddress - ActualAddress) > 200) then
    Exit(0);

  Result := FLines[Index].Line;
end;

{$IF (Defined(MACOS64) and not Defined(IOS)) or Defined(LINUX)}
class function TLineNumberInfo.ReadVarInt(var ABuf: PByte; const ABufEnd: PByte;
  out AValue: UInt32): Boolean;
var
  Value: UInt32;
  Shift: Integer;
  B: Byte;
  P: PByte;
begin
  Value := 0;
  Shift := 0;
  P := ABuf;
  while (True) do
  begin
    if (P >= ABufEnd) then
      Exit(False);

    B := P^;
    Inc(P);

    Value := Value or ((B and $7F) shl Shift);
    if ((B and $80) = 0) then
      Break;

    Inc(Shift, 7);
  end;
  ABuf := P;
  AValue := Value;
  Result := True;
end;
{$ENDIF}

end.
